In [3]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
print(a.dtype)

int64


In [34]:
dt = np.dtype([('user', 'S20'), ('movie', 'S20'), ('rating', 'i4')])

data = np.array([
    (b'Alex', b'My Neighbor Totoro', 5),
    (b'Leah', b'My Neighbor Totoro', 1),
    (b'John', b'My Neighbor Totoro', 4),
    (b'Sadie', b'My Neighbor Totoro', 4),
    (b'Abel', b'My Neighbor Totoro', 2),
    (b'Alex', b'Kiki\'s Delivery Service', 4),
    (b'Leah', b'Kiki\'s Delivery Service', 1),
    (b'John', b'Kiki\'s Delivery Service', 4),
    (b'Sadie', b'Kiki\'s Delivery Service', 5),
    (b'Abel', b'Kiki\'s Delivery Service', 4),
    (   b'Alex', b'Ponyo', 5),
    (b'Leah', b'Ponyo', 4),
    (b'John', b'Ponyo', 3),
    (b'Sadie', b'Ponyo', 4),
    (b'Abel', b'Ponyo', 5)  ,
    (b'Alex', b'Howl\'s Moving Castle', 4),
    (b'Leah', b'Howl\'s Moving Castle', 5),
    (b'John', b'Howl\'s Moving Castle', 1), 
    (b'Sadie', b'Howl\'s Moving Castle', 5),
    (b'Abel', b'Howl\'s Moving Castle', 4),
    (b'Alex', b'Spirited Away', 2),
    (b'Leah', b'Spirited Away', 4),
    (b'John', b'Spirited Away', 5), 
    (b'Sadie', b'Spirited Away', 4),
    (b'Abel', b'Spirited Away', 5),
    (b'Alex', b'Grave of the Fireflies', 4),
    (b'Leah', b'Grave of the Fireflies', 5),
    (b'John', b'Grave of the Fireflies', 4),
    (b'Sadie', b'Grave of the Fireflies', 5),   
    (b'Abel', b'Grave of the Fireflies', 2),
    (b'Alex', b'Castle in the Sky', 5),
    (b'Leah', b'Castle in the Sky', 4),
    (b'John', b'Castle in the Sky', 3),
    (b'Sadie', b'Castle in the Sky', 4),
    (b'Abel', b'Castle in the Sky', 5)  ,
    (b'Alex', b'The Wind Rises', 4),
    (b'Leah', b'The Wind Rises', 3),
    (b'John', b'The Wind Rises', 2),
    (b'Sadie', b'The Wind Rises', 5), 
    (b'Abel', b'The Wind Rises', 4),
    (b'Alex', b'Whisper of the Heart', 5),
    (b'Leah', b'Whisper of the Heart', 4),
    (b'John', b'Whisper of the Heart', 5),
    (b'Sadie', b'Whisper of the Heart', 4),     
    (b'Abel', b'Whisper of the Heart', 5),
    (b'Alex', b'Only Yesterday', 3),
    (b'Leah', b'Only Yesterday', 5),        
    (b'John', b'Only Yesterday', 1),
    (b'Sadie', b'Only Yesterday', 2),
    (b'Abel', b'Only Yesterday', 4)

], dtype=object)
print(data)


[[b'Alex' b'My Neighbor Totoro' 5]
 [b'Leah' b'My Neighbor Totoro' 1]
 [b'John' b'My Neighbor Totoro' 4]
 [b'Sadie' b'My Neighbor Totoro' 4]
 [b'Abel' b'My Neighbor Totoro' 2]
 [b'Alex' b"Kiki's Delivery Service" 4]
 [b'Leah' b"Kiki's Delivery Service" 1]
 [b'John' b"Kiki's Delivery Service" 4]
 [b'Sadie' b"Kiki's Delivery Service" 5]
 [b'Abel' b"Kiki's Delivery Service" 4]
 [b'Alex' b'Ponyo' 5]
 [b'Leah' b'Ponyo' 4]
 [b'John' b'Ponyo' 3]
 [b'Sadie' b'Ponyo' 4]
 [b'Abel' b'Ponyo' 5]
 [b'Alex' b"Howl's Moving Castle" 4]
 [b'Leah' b"Howl's Moving Castle" 5]
 [b'John' b"Howl's Moving Castle" 1]
 [b'Sadie' b"Howl's Moving Castle" 5]
 [b'Abel' b"Howl's Moving Castle" 4]
 [b'Alex' b'Spirited Away' 2]
 [b'Leah' b'Spirited Away' 4]
 [b'John' b'Spirited Away' 5]
 [b'Sadie' b'Spirited Away' 4]
 [b'Abel' b'Spirited Away' 5]
 [b'Alex' b'Grave of the Fireflies' 4]
 [b'Leah' b'Grave of the Fireflies' 5]
 [b'John' b'Grave of the Fireflies' 4]
 [b'Sadie' b'Grave of the Fireflies' 5]
 [b'Abel' b'Grave 

In [35]:
users = np.unique(data[:,0])
movies = np.unique(data[:,1])
print("Unique Users:", users)

Unique Users: [b'Abel' b'Alex' b'John' b'Leah' b'Sadie']


In [ ]:
# creating index maps
users_to_index = {user: index for index, user in enumerate(users)}
movies_to_index = {movie: index for index, movie in enumerate(movies)}

In [ ]:
ratings_matrix = np.zeros((len(users), len(movies)), dtype=int)
for user, movie, rating in data:
    user_index = users_to_index[user]
    movie_index = movies_to_index[movie]
    ratings_matrix[user_index, movie_index] = rating

In [25]:
print("Users:", users)
print("Movies:", movies)
print("Ratings Matrix:\n", ratings_matrix)

Users: [b'Abel' b'Alex' b'John' b'Leah' b'Sadie']
Movies: [b'Castle in the Sky' b'Grave of the Fireflies' b"Howl's Moving Castle"
 b"Kiki's Delivery Service" b'My Neighbor Totoro' b'Only Yesterday'
 b'Ponyo' b'Spirited Away' b'The Wind Rises' b'Whisper of the Heart']
Ratings Matrix:
 [[5 2 4 4 2 4 5 5 4 5]
 [5 4 4 4 5 3 5 2 4 5]
 [3 4 1 4 4 1 3 5 2 5]
 [4 5 5 1 1 5 4 4 3 4]
 [4 5 5 5 4 2 4 4 5 4]]


In [ ]:
#Average rating per movie
average_ratings = np.mean(ratings_matrix, axis=0)
for movie, avg in zip(movies, average_ratings):
    print(f"{movie.decode('utf-8')}: {avg}") 
    
# Sort movies by average rating
sorted_indices = np.argsort(average_ratings)[::-1]  # Sort in descending order
print("\nMovies sorted by average rating:")
for idx in sorted_indices:
    print(f"{movies[idx].decode('utf-8')}: {average_ratings[idx]}")


Castle in the Sky: 4.2
Grave of the Fireflies: 4.0
Howl's Moving Castle: 3.8
Kiki's Delivery Service: 3.6
My Neighbor Totoro: 3.2
Only Yesterday: 3.0
Ponyo: 4.2
Spirited Away: 4.0
The Wind Rises: 3.6
Whisper of the Heart: 4.6

Movies sorted by average rating:
Whisper of the Heart: 4.6
Ponyo: 4.2
Castle in the Sky: 4.2
Grave of the Fireflies: 4.0
Spirited Away: 4.0
Howl's Moving Castle: 3.8
The Wind Rises: 3.6
Kiki's Delivery Service: 3.6
My Neighbor Totoro: 3.2
Only Yesterday: 3.0


In [42]:
#average rating per user
average_user_ratings = np.mean(ratings_matrix, axis=1)
for user, avg in zip(users, average_user_ratings):
    print(f"{user.decode('utf-8')}: {avg}") 
#sorted by average rating
sorted_user_indices = np.argsort(average_user_ratings)[::-1]  # Sort in descending order
print("\nUsers sorted by average rating:")
for idx in sorted_user_indices:
    print(f"{users[idx].decode('utf-8')}: {average_user_ratings[idx]}")
    if average_user_ratings[idx] < 4:
        print(f"{users[idx].decode('utf-8')} is a harsh critic")


Abel: 4.0
Alex: 4.1
John: 3.2
Leah: 3.6
Sadie: 4.2

Users sorted by average rating:
Sadie: 4.2
Alex: 4.1
Abel: 4.0
Leah: 3.6
Leah is a harsh critic
John: 3.2
John is a harsh critic


In [43]:
#top 3 movies
print("\nTop 3 Movies:")
for idx in sorted_indices[:3]:
    print(f"{movies[idx].decode('utf-8')}: {average_ratings[idx]}")
    


Top 3 Movies:
Whisper of the Heart: 4.6
Ponyo: 4.2
Castle in the Sky: 4.2


In [ ]:
#number of good ratings (4 or 5) per movie
good_ratings_count = np.sum(ratings_matrix >= 4, axis=0)
print("\nNumber of good ratings (4 or 5) per movie:")
for movie, count in zip(movies, good_ratings_count):
    print(f"{movie.decode('utf-8')}: {count}")

#sorted by good ratings
sorted_by_good_ratings_indices = np.argsort(good_ratings_count)[::-1]
print("\nMovies sorted by number of good ratings:") 
for idx in sorted_by_good_ratings_indices:
    print(f"{movies[idx].decode('utf-8')}: {good_ratings_count[idx]} good ratings")
        



Number of good ratings (4 or 5) per movie:
Castle in the Sky: 4
Grave of the Fireflies: 4
Howl's Moving Castle: 4
Kiki's Delivery Service: 4
My Neighbor Totoro: 3
Only Yesterday: 2
Ponyo: 4
Spirited Away: 4
The Wind Rises: 3
Whisper of the Heart: 5

Movies sorted by number of good ratings:
Whisper of the Heart: 5 good ratings
Spirited Away: 4 good ratings
Grave of the Fireflies: 4 good ratings
Ponyo: 4 good ratings
Howl's Moving Castle: 4 good ratings
Kiki's Delivery Service: 4 good ratings
Castle in the Sky: 4 good ratings
The Wind Rises: 3 good ratings
My Neighbor Totoro: 3 good ratings
Only Yesterday: 2 good ratings
